base/urls.py
from django.urls import path
from base.api import views as api_views
from .views import (
    InfoListView,
    info_render_pdf_view,
    export,
)
app_name = 'base'

urlpatterns = [
    path('', InfoListView.as_view(),  name='info-base-view'),
    path('pdf/<pk>/', info_render_pdf_view, name='info-pdf-view'),
    path('json/', api_views.django_models_json, name='info-json-view'),
    path('excel/', export, name='excel'),
]

config/urls.py
import os

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("base.urls", namespace='base')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import RegexValidator
# from multiselectfield import MultiSelectField

from base.mychoice import gen_choice


class Department(models.Model):
    name = models.CharField(max_length=100, default="", null=True, blank=True)

    def __str__(self):
        return self.name


class Description(models.Model):
    name = models.CharField(max_length=140, default="", null=True, blank=True)

    def __str__(self):
        return self.name


class Info(models.Model):
    first_name = models.CharField(max_length=150, blank=False)
    last_name = models.CharField(max_length=150, blank=False)
    citizenship = models.CharField(max_length=3, default='GEO', editable=False)
    gen = models.CharField(max_length=10, blank=False, null=False, choices=gen_choice, default="gen choice")
    personal_no = models.CharField(primary_key=True, max_length=11, validators=[RegexValidator(r'^\d{1,11}$')])
    date_of_birth = models.DateField(auto_now_add=False, auto_now=False, blank=False)
    date_of_expiry = models.DateField(auto_now_add=False, auto_now=False, blank=False)
    signature = models.TextField(max_length=100, blank=False)
    card_no = models.CharField(max_length=9, blank=False)
    place_of_birth = models.CharField(max_length=100, blank=False)
    date_of_issue = models.DateTimeField(default=timezone.now)
    issuing_authority = models.TextField(max_length=400, blank=False)
    image = models.ImageField(null=True, blank=True, upload_to='images/', default='default.jpg')

    department = models.ForeignKey(Department, on_delete=models.SET_NULL, default="", blank=True, null=True)
    description = models.ManyToManyField(Description, null=True, blank=True)

    def __str__(self):
        return "{}, {}".format(self.last_name, self.first_name)

base/api/views.py
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from base.models import Info
from base.api.serializers import InfoSerializer


@csrf_exempt
def django_models_json(request):
    """
    List all code snippets, or create a new snippet.
    """
    if request.method == 'GET':
        snippets = Info.objects.all()
        serializer = InfoSerializer(snippets, many=True)
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = InfoSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)

base/views.py
import pandas as pd
from django.shortcuts import render, get_list_or_404
from django.views.decorators.csrf import csrf_exempt
from rest_framework.relations import StringRelatedField

from .models import Info, Department, Description
from .api.serializers import InfoSerializer
from django.http import HttpResponse, JsonResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.generic import ListView

import io
import pandas

from itertools import chain
from django.contrib.postgres.aggregates import ArrayAgg
from django.core import serializers
import json

class InfoListView(ListView):
    model = Info
    template_name = 'base/main.html'


def info_render_pdf_view(request, *args, **kwargs):
    pk = kwargs.get('pk')
    info = get_list_or_404(Info, pk=pk)

    template_path = 'base/to_pdf.html'
    context = {'info': info}

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="report.pdf"'
    template = get_template(template_path)
    html = template.render(context)

    pisa_status = pisa.CreatePDF(
        html, dest=response)
    if pisa_status.err:
        return render('We had some errors <pre>' + html + '</pre>')
    return response


def data_frame_to_io(data_frame: pandas.DataFrame, sheet_name='Export') -> bytes:
    data_stream = io.BytesIO()
    writer = pandas.ExcelWriter(data_stream, engine='xlsxwriter')
    data_frame.to_excel(writer, index=False, sheet_name=sheet_name)
    writer.save()
    data_stream.seek(0)

    return data_stream.getvalue()


def export(request):
    snippets = Info.objects.all()
    serializer = InfoSerializer(snippets, many=True)
    data = serializer.data

    results = pandas.DataFrame(data=data)
    # results['date_of_issue'] = results['date_of_issue'].apply(lambda a: pd.to_datetime(a).date())
    file_data = data_frame_to_io(results)
    response = HttpResponse(file_data, content_type='application/octet-stream')
    response['Content-Disposition'] = 'attachment; filename="export.xlsx"'

    return response

base/templates/base/base.html
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Info | {% block title %}{% endblock title %} </title>
  </head>
  <body>
    <div class="container">
        {% block content %}
        
        {% endblock content %}
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

base/templates/base/main.html
{% extends 'base/base.html' %}
{% block title %}
base
{% endblock title%}
{% block content %}
    {% for field in object_list %}
        <hr>
        <img src="{{ field.image.url }}" alt="" height="200px" width="200px">
        <dl>
            <dt>FIRST NAME</dt>
            <dd>{{ field.first_name }}</dd>
            <dt>LAST NAME</dt>
            <dd>{{ field.last_name }}</dd>
            <dt>CIT</dt>
            <dd>{{ field.citizenship }}</dd>
            <dt>GEN</dt>
            <dd>{{ field.gen }}</dd>
            <dt>PERSONAL NO</dt>
            <dd>{{ field.personal_no }}</dd>
            <dt>DATE OF BIRTH</dt>
            <dd>{{ field.date_of_birth|date:"F d, Y" }}</dd>
            <dt>DATE OF EXPIRY</dt>
            <dd>{{ field.date_of_expiry|date:"F d, Y" }}</dd>
            <dt>SIGNATURE</dt>
            <dd>{{ field.signature }}</dd>
            <dt>CARD No</dt>
            <dd>{{ field.card_no }}</dd>
            <dt>PLACE OF BIRTH</dt>
            <dd>{{ field.place_of_birth }}</dd>
            <dt>DATE OF ISSUE</dt>
            <dd>{{ field.date_of_issue|date:"F d, Y" }}</dd>
            <dt>ISSUING AUTHORITY</dt>
            <dd>{{ field.issuing_authority }}</dd>
            {% if field.department %}
                <dt>DEPARTMENT</dt>
                <dd>{{ field.department }}</dd>
            {% endif %}
            {% if field.description %}
                <dt>DESCRIPTION</dt>
                {% for description in field.description.all %}
                    {{ description }}
                {% endfor %}
            {% endif %}



        </dl>

        <br>

        <a href="{% url 'base:info-pdf-view' field.pk %}"><button class="btn btn-primary">pdf</button></a>

        <br>
        <hr>
    {% endfor %}
    <div style="position: absolute; top: 0; right: 0; margin: 20px">
    {% if object_list %}
        <a href="{% url 'base:excel' %}"><button class="btn btn-primary">excel</button></a>
        <a href="{% url 'base:info-json-view' %}"><button class="btn btn-primary">json</button></a>
    {% endif %}
    </div>
{% endblock content %}

base/templates/base/to_pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PDF Test</title>
    <style>
        dt {
            font-size: 15px;
            font-weight: bold;
        }
        dd {
            font-size: 13px;
        }
    </style>
</head>
<body>
    {% for field in info %}
        <img src="{{ field.image.path }}" alt="" height="240px" width="240px">
        <br><br>
        <dt>FIRST NAME</dt>
        <dd>{{ field.first_name }}</dd>
        <dt>LAST NAME</dt>
        <dd>{{ field.last_name }}</dd>
        <dt>CIT</dt>
        <dd>{{ field.citizenship }}</dd>
        <dt>GEN</dt>
        <dd>{{ field.gen }}</dd>
        <dt>PERSONAL NO</dt>
        <dd>{{ field.personal_no }}</dd>
        <dt>DATE OF BIRTH</dt>
        <dd>{{ field.date_of_birth|date:"F d, Y" }}</dd>
        <dt>DATE OF EXPIRY</dt>
        <dd>{{ field.date_of_expiry|date:"F d, Y" }}</dd>
        <dt>SIGNATURE</dt>
        <dd>{{ field.signature }}</dd>
        <dt>CARD No</dt>
        <dd>{{ field.card_no }}</dd>
        <dt>PLACE OF BIRTH</dt>
        <dd>{{ field.place_of_birth }}</dd>
        <dt>DATE OF ISSUE</dt>
        <dd>{{ field.date_of_issue|date:"F d, Y" }}</dd>
        <dt>ISSUING AUTHORITY</dt>
        <dd>{{ field.issuing_authority }}</dd>
        {% if field.department %}
            <dt>DEPARTMENT</dt>
            <dd>{{ field.department }}</dd>
        {% endif %}
        {% if field.description %}
            <dt>DESCRIPTION</dt>
            {% for description in field.description.all %}
                {{ description }}
            {% endfor %}
        {% endif %}
    {% endfor %}
</body>
</html>